<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="ZenFlow.Tests\**\*.cs" />
		<EmbeddedResource Remove="ZenFlow.Tests\**\*" />
		<None Remove="ZenFlow.Tests\**\*" />
		<Page Remove="ZenFlow.Tests\**\*.xaml" />
	</ItemGroup>

</Project>