name: CI - Build and Test

on:
  push:
    branches:
      - main
      - pipeline-ci

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ZenFlow

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar solución
        run: dotnet build --configuration Release --no-restore

      - name: Ejecutar pruebas
        run: dotnet test --configuration Release --no-build --verbosity normal